<?xml version='1.0' encoding='UTF-8'?><definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://teiid.org" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:schema2="http://www.metamatrix.com/Contact_Output" xmlns:schema1="http://www.metamatrix.com/Contact_Input" xmlns="http://schemas.xmlsoap.org/wsdl/" name="Salesforce_VDB" targetNamespace="http://teiid.org">
  <types>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://teiid.org" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:schema2="http://www.metamatrix.com/Contact_Output" xmlns:schema1="http://www.metamatrix.com/Contact_Input" xmlns="http://schemas.xmlsoap.org/wsdl/" targetNamespace="http://teiid.org">
      <xsd:import namespace="http://www.metamatrix.com/Contact_Input" schemaLocation="Salesforce_VBL_Input.xsd"/>
      <xsd:import namespace="http://www.metamatrix.com/Contact_Output" schemaLocation="Salesforce_VBL_Output.xsd"/>
    </xsd:schema>
  </types>
  <message name="Salesforce_VBL_Contact_getContact_Contact_OutputMsg">
<documentation>Output message for operation Salesforce_VBL_Contact/getContact.</documentation>
    <part element="schema2:Contact_Output" name="Salesforce_VBL_Contact_getContact_Contact_OutputMsg">
    </part>
  </message>
  <message name="Salesforce_VBL_Contact_getContact_Contact_InputMsg">
<documentation>Input message for operation Salesforce_VBL_Contact/getContact.</documentation>
    <part element="schema1:Contact_Input" name="Salesforce_VBL_Contact_getContact_Contact_InputMsg">
    </part>
  </message>
  <portType name="Salesforce_VBL_Contact">
    <operation name="getContact">
      <input message="tns:Salesforce_VBL_Contact_getContact_Contact_InputMsg">
    </input>
      <output message="tns:Salesforce_VBL_Contact_getContact_Contact_OutputMsg">
    </output>
    </operation>
  </portType>
  <binding name="Salesforce_VBL_Contact" type="tns:Salesforce_VBL_Contact">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="getContact">
      <soap:operation soapAction="getContact" style="document"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="Salesforce_VDB">
    <port binding="tns:Salesforce_VBL_Contact" name="Salesforce_VBL_Contact">
      <soap:address location="http://datavirt:8080/Salesforce_VDB/Salesforce_VBL_Contact"/>
    </port>
  </service>
</definitions>